spring.application.name=chat-management-system

server.servlet.context-path=/api

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/chat-management-system
spring.datasource.username=postgres
spring.datasource.password=Innodeed@123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Properties (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Execute SQL file on Startup
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

api.key=cms12345
allowedorigins=*

# Enable debug logging globally
debug=true

logging.level.org.springframework.security=DEBUG
logging.level.com.yourpackage=DEBUG
